import { 
  Home, Bell, Mail, Clock, MapPin, Heart, RefreshCw, User, Sliders, Calendar, Settings, ShoppingCart, Eye, PlusCircle, MinusCircle, Wallet, Download, Tag,
  Activity, AlertCircle, Archive, Award, BarChart, Battery, Bluetooth, Book, Bookmark, Box, Briefcase, Camera, Check, Clipboard, Cloud, Coffee, Compass, Copy, Cpu, CreditCard, Crosshair, Database, DollarSign, Droplet, Edit, Edit2, FastForward, Feather, File, FileText, Film, Filter, Flag, Folder, Gift, Globe, Grid, HardDrive, Headphones, HelpCircle, Hexagon, Inbox, Info, Key, Layers, Layout, LifeBuoy, Link, List, Lock, LogIn, LogOut, Map, MessageCircle, MessageSquare, Mic, Monitor, Moon, Music, Navigation, Package, Paperclip, Pause, Percent, Phone, PieChart, Play, Plus, Power, Printer, Radio, Save, Scissors, Search, Send, Server, Share, Shield, ShoppingBag, Smartphone, Smile, Speaker, Star, Sun, Tablet, Target, Terminal, Thermometer, ThumbsDown, ThumbsUp, Trash, Trash2, TrendingDown, TrendingUp, Truck, Tv, Umbrella, Unlock, Upload, Users, Video, Watch, Wifi, Wind, Zap, ZoomIn, ZoomOut,
  Car, Plane, Train, Bus, Bike, Ship, Fuel, Ticket,
  Utensils, Wine, Pizza, Apple, Beef, Carrot, Cherry, Citrus, Croissant, Egg, Fish, Grape, IceCream, Martini, Milk, Nut, Salad, Sandwich, Soup, Vegan,
  Building, Building2, Factory, Store, Warehouse, Hotel, School, Hospital,
  Cat, Dog, Bird, Rabbit, Snail, Turtle, Bug,
  Gamepad, Gamepad2, Puzzle, Ghost, Sparkles, Wand, Clapperboard, Popcorn, PartyPopper, Tent, Trees, Mountain,
  Dumbbell, HeartPulse, Stethoscope, Pill,
  Barcode, Shirt, Brush, Glasses,
  Wrench, Hammer, Drill, Construction,
  GraduationCap, PenTool, Pencil, Library,
  Bitcoin, Banknote, Coins, PiggyBank, Landmark, Scale,
  Calculator, Baby, Contact
} from 'lucide-react';

export const ICON_OPTIONS = [
  { name: 'Tag', icon: Tag }, { name: 'Home', icon: Home }, { name: 'Bell', icon: Bell }, { name: 'Mail', icon: Mail },
  { name: 'Clock', icon: Clock }, { name: 'MapPin', icon: MapPin }, { name: 'Heart', icon: Heart }, { name: 'RefreshCw', icon: RefreshCw },
  { name: 'User', icon: User }, { name: 'Sliders', icon: Sliders }, { name: 'Calendar', icon: Calendar }, { name: 'Settings', icon: Settings },
  { name: 'ShoppingCart', icon: ShoppingCart }, { name: 'Eye', icon: Eye }, { name: 'PlusCircle', icon: PlusCircle }, { name: 'MinusCircle', icon: MinusCircle },
  { name: 'Wallet', icon: Wallet }, { name: 'Download', icon: Download }, { name: 'Activity', icon: Activity }, { name: 'AlertCircle', icon: AlertCircle },
  { name: 'Archive', icon: Archive }, { name: 'Award', icon: Award }, { name: 'BarChart', icon: BarChart }, { name: 'Battery', icon: Battery },
  { name: 'Bluetooth', icon: Bluetooth }, { name: 'Book', icon: Book }, { name: 'Bookmark', icon: Bookmark }, { name: 'Box', icon: Box },
  { name: 'Briefcase', icon: Briefcase }, { name: 'Camera', icon: Camera }, { name: 'Check', icon: Check }, { name: 'Clipboard', icon: Clipboard },
  { name: 'Cloud', icon: Cloud }, { name: 'Coffee', icon: Coffee }, { name: 'Compass', icon: Compass }, { name: 'Copy', icon: Copy },
  { name: 'Cpu', icon: Cpu }, { name: 'CreditCard', icon: CreditCard }, { name: 'Crosshair', icon: Crosshair }, { name: 'Database', icon: Database },
  { name: 'DollarSign', icon: DollarSign }, { name: 'Droplet', icon: Droplet }, { name: 'Edit', icon: Edit }, { name: 'Edit2', icon: Edit2 },
  { name: 'FastForward', icon: FastForward }, { name: 'Feather', icon: Feather }, { name: 'File', icon: File }, { name: 'FileText', icon: FileText },
  { name: 'Film', icon: Film }, { name: 'Filter', icon: Filter }, { name: 'Flag', icon: Flag }, { name: 'Folder', icon: Folder },
  { name: 'Gift', icon: Gift }, { name: 'Globe', icon: Globe }, { name: 'Grid', icon: Grid }, { name: 'HardDrive', icon: HardDrive },
  { name: 'Headphones', icon: Headphones }, { name: 'HelpCircle', icon: HelpCircle }, { name: 'Hexagon', icon: Hexagon }, { name: 'Inbox', icon: Inbox },
  { name: 'Info', icon: Info }, { name: 'Key', icon: Key }, { name: 'Layers', icon: Layers }, { name: 'Layout', icon: Layout },
  { name: 'LifeBuoy', icon: LifeBuoy }, { name: 'Link', icon: Link }, { name: 'List', icon: List }, { name: 'Lock', icon: Lock },
  { name: 'LogIn', icon: LogIn }, { name: 'LogOut', icon: LogOut }, { name: 'Map', icon: Map }, { name: 'MessageCircle', icon: MessageCircle },
  { name: 'MessageSquare', icon: MessageSquare }, { name: 'Mic', icon: Mic }, { name: 'Monitor', icon: Monitor }, { name: 'Moon', icon: Moon },
  { name: 'Music', icon: Music }, { name: 'Navigation', icon: Navigation }, { name: 'Package', icon: Package }, { name: 'Paperclip', icon: Paperclip },
  { name: 'Pause', icon: Pause }, { name: 'Percent', icon: Percent }, { name: 'Phone', icon: Phone }, { name: 'PieChart', icon: PieChart },
  { name: 'Play', icon: Play }, { name: 'Plus', icon: Plus }, { name: 'Power', icon: Power },
  { name: 'Printer', icon: Printer }, { name: 'Radio', icon: Radio }, { name: 'Save', icon: Save }, { name: 'Scissors', icon: Scissors },
  { name: 'Search', icon: Search }, { name: 'Send', icon: Send }, { name: 'Server', icon: Server }, { name: 'Share', icon: Share },
  { name: 'Shield', icon: Shield }, { name: 'ShoppingBag', icon: ShoppingBag }, { name: 'Smartphone', icon: Smartphone }, { name: 'Smile', icon: Smile },
  { name: 'Speaker', icon: Speaker }, { name: 'Star', icon: Star }, { name: 'Sun', icon: Sun }, { name: 'Tablet', icon: Tablet },
  { name: 'Target', icon: Target }, { name: 'Terminal', icon: Terminal }, { name: 'Thermometer', icon: Thermometer }, { name: 'ThumbsDown', icon: ThumbsDown },
  { name: 'ThumbsUp', icon: ThumbsUp }, { name: 'Trash', icon: Trash }, { name: 'Trash2', icon: Trash2 },
  { name: 'TrendingDown', icon: TrendingDown }, { name: 'TrendingUp', icon: TrendingUp }, { name: 'Truck', icon: Truck }, { name: 'Tv', icon: Tv },
  { name: 'Umbrella', icon: Umbrella }, { name: 'Unlock', icon: Unlock }, { name: 'Upload', icon: Upload }, { name: 'Users', icon: Users },
  { name: 'Video', icon: Video }, { name: 'Watch', icon: Watch }, { name: 'Wifi', icon: Wifi }, { name: 'Wind', icon: Wind },
  { name: 'Zap', icon: Zap }, { name: 'ZoomIn', icon: ZoomIn }, { name: 'ZoomOut', icon: ZoomOut },
  { name: 'Car', icon: Car }, { name: 'Plane', icon: Plane }, { name: 'Train', icon: Train }, { name: 'Bus', icon: Bus },
  { name: 'Bike', icon: Bike }, { name: 'Ship', icon: Ship }, { name: 'Fuel', icon: Fuel }, { name: 'Ticket', icon: Ticket },
  { name: 'Utensils', icon: Utensils }, { name: 'Wine', icon: Wine }, { name: 'Pizza', icon: Pizza }, { name: 'Apple', icon: Apple },
  { name: 'Beef', icon: Beef }, { name: 'Carrot', icon: Carrot }, { name: 'Cherry', icon: Cherry }, { name: 'Citrus', icon: Citrus },
  { name: 'Croissant', icon: Croissant }, { name: 'Egg', icon: Egg }, { name: 'Fish', icon: Fish }, { name: 'Grape', icon: Grape },
  { name: 'IceCream', icon: IceCream }, { name: 'Martini', icon: Martini }, { name: 'Milk', icon: Milk }, { name: 'Nut', icon: Nut },
  { name: 'Salad', icon: Salad }, { name: 'Sandwich', icon: Sandwich }, { name: 'Soup', icon: Soup }, { name: 'Vegan', icon: Vegan },
  { name: 'Building', icon: Building }, { name: 'Building2', icon: Building2 }, { name: 'Factory', icon: Factory }, { name: 'Store', icon: Store },
  { name: 'Warehouse', icon: Warehouse }, { name: 'Hotel', icon: Hotel }, { name: 'School', icon: School }, { name: 'Hospital', icon: Hospital },
  { name: 'Cat', icon: Cat }, { name: 'Dog', icon: Dog }, { name: 'Bird', icon: Bird }, { name: 'Rabbit', icon: Rabbit },
  { name: 'Snail', icon: Snail }, { name: 'Turtle', icon: Turtle }, { name: 'Bug', icon: Bug },
  { name: 'Gamepad', icon: Gamepad }, { name: 'Gamepad2', icon: Gamepad2 }, { name: 'Puzzle', icon: Puzzle }, { name: 'Ghost', icon: Ghost },
  { name: 'Sparkles', icon: Sparkles }, { name: 'Wand', icon: Wand }, { name: 'Clapperboard', icon: Clapperboard }, { name: 'Popcorn', icon: Popcorn },
  { name: 'PartyPopper', icon: PartyPopper }, { name: 'Tent', icon: Tent }, { name: 'Trees', icon: Trees }, { name: 'Mountain', icon: Mountain },
  { name: 'Dumbbell', icon: Dumbbell }, { name: 'HeartPulse', icon: HeartPulse }, { name: 'Stethoscope', icon: Stethoscope }, { name: 'Pill', icon: Pill },
  { name: 'Barcode', icon: Barcode }, { name: 'Shirt', icon: Shirt }, { name: 'Brush', icon: Brush }, { name: 'Glasses', icon: Glasses },
  { name: 'Wrench', icon: Wrench }, { name: 'Hammer', icon: Hammer }, { name: 'Drill', icon: Drill }, { name: 'Construction', icon: Construction },
  { name: 'GraduationCap', icon: GraduationCap }, { name: 'PenTool', icon: PenTool }, { name: 'Pencil', icon: Pencil }, { name: 'Library', icon: Library },
  { name: 'Bitcoin', icon: Bitcoin }, { name: 'Banknote', icon: Banknote }, { name: 'Coins', icon: Coins }, { name: 'PiggyBank', icon: PiggyBank },
  { name: 'Landmark', icon: Landmark }, { name: 'Scale', icon: Scale }, { name: 'Calculator', icon: Calculator }, { name: 'Baby', icon: Baby },
  { name: 'Contact', icon: Contact }
];
